name: Publish to Cargo

# Auto-generates Git tags corresponding to changes in Cargo.toml, and publishes
# to crates.io

on:
  workflow_dispatch:
  push:
    paths:
      - "Cargo.toml"
    branches: [main]

    # Reference your environment variables
    environment: cargo

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          # get git tags info
          fetch-depth: 0

      - name: Publish
        uses: seaofvoices/rust-release-action@v1
        with:
          publish_crate: true
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
